const mongoose = require("mongoose");
require("dotenv").config();
const Recipe = require("./models/Recipe");

const recipes = [
  {
    recipeName: "Creamy Garlic Pasta",
    recipeImage: "/recipes/goodfood.jpg",
    category: "Dinner",
    cuisineType: "Italian",
    difficultyLevel: "Easy",
    preparationTime: 25,
    ingredients: ["Pasta", "Garlic", "Cream", "Parmesan", "Butter"],
    instructions: "Boil pasta, prepare creamy garlic sauce, combine, and serve hot.",
    authorId: "u1",
    authorName: "Sophia Carter",
    authorEmail: "sophia@example.com",
    likesCount: 1240,
    isFeatured: true,
    status: "active",
  },
  {
    recipeName: "Spicy Chicken Ramen",
    recipeImage: "/recipes/goodfood.jpg",
    category: "Lunch",
    cuisineType: "Japanese",
    difficultyLevel: "Medium",
    preparationTime: 35,
    ingredients: ["Ramen noodles", "Chicken", "Broth", "Chili oil", "Egg"],
    instructions: "Cook broth, prepare chicken, boil noodles, and assemble the ramen bowl.",
    authorId: "u2",
    authorName: "Ayaan Malik",
    authorEmail: "ayaan@example.com",
    likesCount: 892,
    isFeatured: false,
    status: "active",
  },
  {
    recipeName: "Berry Pancake Stack",
    recipeImage: "/recipes/goodfood.jpg",
    category: "Breakfast",
    cuisineType: "American",
    difficultyLevel: "Easy",
    preparationTime: 20,
    ingredients: ["Flour", "Eggs", "Milk", "Berries", "Maple syrup"],
    instructions: "Mix batter, cook pancakes on griddle, stack with berries and syrup.",
    authorId: "u3",
    authorName: "Nadia Rahman",
    authorEmail: "nadia@example.com",
    likesCount: 756,
    isFeatured: true,
    status: "active",
  },
  {
    recipeName: "Avocado Toast",
    recipeImage: "/recipes/goodfood.jpg",
    category: "Breakfast",
    cuisineType: "Australian",
    difficultyLevel: "Easy",
    preparationTime: 10,
    ingredients: ["Bread", "Avocado", "Lemon", "Salt", "Pepper"],
    instructions: "Toast bread, mash avocado, spread on toast, season and serve.",
    authorId: "u1",
    authorName: "Sophia Carter",
    authorEmail: "sophia@example.com",
    likesCount: 423,
    isFeatured: false,
    status: "active",
  },
  {
    recipeName: "Butter Chicken Bowl",
    recipeImage: "/recipes/goodfood.jpg",
    category: "Dinner",
    cuisineType: "Indian",
    difficultyLevel: "Medium",
    preparationTime: 45,
    ingredients: ["Chicken", "Butter", "Cream", "Tomato puree", "Spices"],
    instructions: "Marinate chicken, cook in butter-tomato sauce, serve with rice or naan.",
    authorId: "u2",
    authorName: "Ayaan Malik",
    authorEmail: "ayaan@example.com",
    likesCount: 1102,
    isFeatured: false,
    status: "active",
  },
  {
    recipeName: "Classic Caesar Salad",
    recipeImage: "/recipes/goodfood.jpg",
    category: "Lunch",
    cuisineType: "Italian",
    difficultyLevel: "Easy",
    preparationTime: 15,
    ingredients: ["Lettuce", "Croutons", "Parmesan", "Caesar dressing", "Chicken"],
    instructions: "Chop lettuce, grill chicken, toss with dressing and croutons, top with parmesan.",
    authorId: "u3",
    authorName: "Nadia Rahman",
    authorEmail: "nadia@example.com",
    likesCount: 567,
    isFeatured: false,
    status: "active",
  },
  {
    recipeName: "Thai Basil Noodles",
    recipeImage: "/recipes/goodfood.jpg",
    category: "Dinner",
    cuisineType: "Thai",
    difficultyLevel: "Medium",
    preparationTime: 30,
    ingredients: ["Rice noodles", "Basil", "Chili", "Garlic", "Soy sauce"],
    instructions: "Stir-fry noodles with garlic and chili, add basil and soy sauce, serve hot.",
    authorId: "u1",
    authorName: "Sophia Carter",
    authorEmail: "sophia@example.com",
    likesCount: 689,
    isFeatured: true,
    status: "active",
  },
  {
    recipeName: "Mushroom Risotto",
    recipeImage: "/recipes/goodfood.jpg",
    category: "Dinner",
    cuisineType: "Italian",
    difficultyLevel: "Hard",
    preparationTime: 50,
    ingredients: ["Arborio rice", "Mushrooms", "White wine", "Parmesan", "Vegetable broth"],
    instructions: "Sauté mushrooms, toast rice, deglaze with wine, slowly add broth while stirring.",
    authorId: "u2",
    authorName: "Ayaan Malik",
    authorEmail: "ayaan@example.com",
    likesCount: 445,
    isFeatured: false,
    status: "active",
  },
  {
    recipeName: "Chocolate Lava Cake",
    recipeImage: "/recipes/goodfood.jpg",
    category: "Dessert",
    cuisineType: "French",
    difficultyLevel: "Hard",
    preparationTime: 30,
    ingredients: ["Dark chocolate", "Butter", "Eggs", "Sugar", "Flour"],
    instructions: "Melt chocolate and butter, fold in eggs and sugar, bake until edges set.",
    authorId: "u3",
    authorName: "Nadia Rahman",
    authorEmail: "nadia@example.com",
    likesCount: 934,
    isFeatured: true,
    status: "active",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  await Recipe.deleteMany({});
  await Recipe.insertMany(recipes);
  console.log(`Seeded ${recipes.length} recipes`);
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
